name: Terraform apply infra change

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: dev
    needs: []
    runs-on: ubuntu-latest
    steps:
     - run: echo "running dev stage"

  1:
    uses: ./.github/workflows/site-cd-workflow.yml
    with:
      working-directory: dev/1
    secrets: inherit
    needs: [dev]

  sample:
    uses: ./.github/workflows/site-cd-workflow.yml
    with:
      working-directory: dev/sample
    secrets: inherit
    needs: [dev]

  1:
    uses: ./.github/workflows/site-cd-workflow.yml
    with:
      working-directory: dev/1
    secrets: inherit
    needs: [dev]

  qa:
    name: qa
    needs: [1,sample,1,dev]
    runs-on: ubuntu-latest
    steps:
     - run: echo "running qa stage"

  prod:
    name: prod
    needs: [qa]
    runs-on: ubuntu-latest
    steps:
     - run: echo "running prod stage"
